### ISSUE TITLE
Sniffer support

### ISSUE THREAD

**Issue by techniq** [n8henrie/node-rcswitch-gpiomem#4]
First, thank you very much for this root-less implementation.

I'm currently working on creating a node-red library/node to transmit and receive 433Mhz codes.  Initially I tried using https://github.com/eroak/rpi-433 (which I've had success with outside of node-red) but ran into limitations due to it's root requirement.  I currently have transmitting working with your library, but would love to also implement receiving/sniffing.

Would it be possible to add a root-less sniffing implementation?  Thanks.

**Comment by n8henrie** [comment]
I agree that receiving would be a good addition -- unfortunately, my javascript and C++ are very limited, and just getting the project to this point took more time and effort than I'm happy to admit. Because I don't have a use case for this feature and other projects require my time, I don't think I'll be able to implement it.

If you or anybody else wants to make a PR please feel free. I'll leave the issue open for 10 days or so to see if it stimulates any conversation.

**Comment by techniq** [comment]
@n8henrie No worries.  I have an [issue](https://github.com/eroak/rpi-433/issues/7) open on rpi-433 to use `/dev/gpiomem` for both it's send/transmit as well as it's receive/sniffer code (it supports both, but requires root).  I might take a stab at adding root-less support that library if I find some time myself.  Currently I'm just experimenting with home automation / node-red and found this to be a nice addition to node-red to control 433Mhz devices (ie. lights).

Thanks for getting back with me for taking the time to release this library.  Worst case, it gives me some good insight on how to update rpi-433.  Feel free to close this issue now (or leave it open for the 10 days just in case others want to chime in).
