### ISSUE TITLE
Can't build RCSwitch on Node>v11

### ISSUE THREAD

**Issue by jdtsmith** [n8henrie/node-rcswitch-gpiomem#6]
This is due to the removal of V8 functions `Int32Value`, `Uint32Value`, `GetFunction`, etc. Latest node is now v13.2.0.  [This post](https://github.com/bcoin-org/bcrypto/issues/7#issuecomment-498964097) discusses a possible solution at least for the value types.

**Comment by n8henrie** [comment]
Thanks for the heads up. I have to admit that I don't use javascript much -- do you happen to know offhand if these changes should be backwards compatible?

**Comment by jdtsmith** [comment]
In the sense that they're back-ported to older Node versions?  Not sure of that.  But you could probably just drop support for such old versions?

**Comment by n8henrie** [comment]
Fair enough.

Honestly, I haven't used this library in several years. Pull requests are more than welcome, but I am unlikely to invest time myself to fix this anytime soon. I'll leave this issue open for a while in case there are any volunteers, but otherwise will likely just label the project as requiring node<=v11.

Thanks again for the report.

**Comment by n8henrie** [comment]
As noted, I don't know much javascript, and since I'm not using this library, haven't updated the code in >=4y, and have not seen any volunteer contributions to help address it, I think it's reasonable to archive the repo. Please get in touch if anyone would like to contribute a fix, or please feel free to fork.
